Instance: twss-nationality-to-iso3166
InstanceOf: ConceptMap
Usage: #definition
Title: "TWSS 國籍對應 ISO 3166-1 alpha-2"
Description: "TWSS 國籍代碼系統與 ISO 3166-1 alpha-2 國碼之對應。"
* name = "TWSSNationalityToISO3166"
* version = "0.0.1"
* status = #draft
* experimental = false
* sourceCanonical = Canonical(TWSSNationalityVS)
* targetCanonical = "http://hl7.org/fhir/ValueSet/iso3166-1-2"
* group[0].source = "https://sfaa.gov.tw/base/CodeSystem/twss-nationality"
* group[0].target = "urn:iso:std:iso:3166"
* group[0].element[0].code = #0
* group[0].element[0].display = "本國籍"
* group[0].element[0].target[0].code = #TW
* group[0].element[0].target[0].display = "Taiwan"
* group[0].element[0].target[0].equivalence = #equivalent
* group[0].element[1].code = #1
* group[0].element[1].display = "日本"
* group[0].element[1].target[0].code = #JP
* group[0].element[1].target[0].display = "Japan"
* group[0].element[1].target[0].equivalence = #equivalent
* group[0].element[2].code = #2
* group[0].element[2].display = "法國"
* group[0].element[2].target[0].code = #FR
* group[0].element[2].target[0].display = "France"
* group[0].element[2].target[0].equivalence = #equivalent
* group[0].element[3].code = #3
* group[0].element[3].display = "英國"
* group[0].element[3].target[0].code = #GB
* group[0].element[3].target[0].display = "United Kingdom"
* group[0].element[3].target[0].equivalence = #equivalent
* group[0].element[4].code = #4
* group[0].element[4].display = "美國"
* group[0].element[4].target[0].code = #US
* group[0].element[4].target[0].display = "United States"
* group[0].element[4].target[0].equivalence = #equivalent
* group[0].element[5].code = #5
* group[0].element[5].display = "柬埔寨"
* group[0].element[5].target[0].code = #KH
* group[0].element[5].target[0].display = "Cambodia"
* group[0].element[5].target[0].equivalence = #equivalent
* group[0].element[6].code = #6
* group[0].element[6].display = "泰國"
* group[0].element[6].target[0].code = #TH
* group[0].element[6].target[0].display = "Thailand"
* group[0].element[6].target[0].equivalence = #equivalent
* group[0].element[7].code = #7
* group[0].element[7].display = "印尼"
* group[0].element[7].target[0].code = #ID
* group[0].element[7].target[0].display = "Indonesia"
* group[0].element[7].target[0].equivalence = #equivalent
* group[0].element[8].code = #8
* group[0].element[8].display = "越南"
* group[0].element[8].target[0].code = #VN
* group[0].element[8].target[0].display = "Viet Nam"
* group[0].element[8].target[0].equivalence = #equivalent
* group[0].element[9].code = #9
* group[0].element[9].display = "中國大陸"
* group[0].element[9].target[0].code = #CN
* group[0].element[9].target[0].display = "China"
* group[0].element[9].target[0].equivalence = #equivalent
* group[0].element[10].code = #10
* group[0].element[10].display = "無國籍"
* group[0].element[10].target[0].equivalence = #unmatched
* group[0].element[10].target[0].comment = "無國籍不是國家，無法對應 ISO 3166-1 國碼。"
* group[0].element[11].code = #11
* group[0].element[11].display = "外國籍(不確定國家)"
* group[0].element[11].target[0].equivalence = #unmatched
* group[0].element[11].target[0].comment = "未能明確表示國家，無法對應 ISO 3166-1 國碼。"
* group[0].element[12].code = #99
* group[0].element[12].display = "其他"
* group[0].element[12].target[0].equivalence = #unmatched
* group[0].element[12].target[0].comment = "其他未明確表示國家，無法對應 ISO 3166-1 國碼。"
* group[0].element[13].code = #X
* group[0].element[13].display = "不詳"
* group[0].element[13].target[0].equivalence = #unmatched
* group[0].element[13].target[0].comment = "不詳無法對應 ISO 3166-1 國碼。"
